@startuml
class Animation {
// playedOnce = false
- constructor():
==
// calculate elapsed_time
// update currentFrame and startTime
// based on delay, currentFrames and frame length
+ update(): void
+ setter()
+ getter()
+ setFrames(BufferedImage[] frames): void
--
BufferedImage[] frames
int currentFrame
long startTime
long delay
boolean playedOnce
}
@enduml