@startuml
class Player extends MapObject {
// manual assigning all atr
// also load sprites
// and putting sfxs
- constructor(TileMap)
==
// loop through enemies
// check check attacks
// check if intersects
+ checkAttack(ArrayList<Enemy> enemy): void
+ hit(int damage): void
+ getNextPosition(): void
+ update(): void
+ draw():void @override
+ getter()
--ENUMS--
int IDLE = 0
int WALKING = 1
int JUMPING = 2
int FALLING = 3
int LIGHTNING = 4
int SCRATCHING = 5
--sound--
HashMap<String, AudioPlayer> sfx
--player stuff--
int health
int maxHealth
int fire
int maxFire
boolean dead
boolean flinching
long flinchTimer
--lightning--
boolean firing
int lightningCost
int lightningDamage
ArrayList<Lightning> lightnings
--scratch--
boolean scratching
int scratchDamage
int scratchRange
--animations--
ArrayList<BufferedImage[]> sprites
final int[] numFrames = {
    2, 8, 1, 2, 4, 2, 5
}; // TODO: change
}
@enduml